vich_uploader:
    db_driver: orm

    mappings:
       cours_image:
           uri_prefix: /imgVich
           upload_destination: '%kernel.project_dir%/public/imgVich'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
